apiVersion: v1
kind: Service
metadata:
  name: alert-notifier-service
  namespace: dsbd
spec:
  selector:
    app: alert-notifier-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084