apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../config
  - ../infra/postgres
  - ../infra/kafka
  - ../apps/user-manager-service
  - ../apps/data-collector-service
  - ../apps/alert-system-service
  - ../apps/alert-notifier-service
  - ../apps/api-gateway