apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
  namespace: dsbd
spec:
  selector:
    app: data-collector-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082