spring:
  application:
    name: data-collector-service

  datasource:
    url: jdbc:postgresql://localhost:5432/datadb
    username: user        # stesso utente del container postgres
    password: password    # stessa password del container postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

grpc:
  server:
    port: -1          # disabilita il server gRPC esterno
  client:
    user-manager:
      address: static://localhost:9090
      negotiationType: plaintext

opensky:
  auth-url: "https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token"
  api-base-url: "https://opensky-network.org/api"
  client-id: "stefanocaramagno-api-client"
  client-secret: "yi9yeSODPHIzWHQq6YAnaDYZOpq9061l"



