apiVersion: v1
kind: ConfigMap
metadata:
  name: dsbd-config
  namespace: dsbd
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USERNAME: user
  USER_DB_NAME: userdb
  DATA_DB_NAME: datadb

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  OPENSKY_AUTH_URL: https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token
  OPENSKY_API_URL: https://opensky-network.org/api

  MAIL_HOST: sandbox.smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_SMTP_AUTH: "true"
  MAIL_SMTP_STARTTLS_ENABLE: "true"
  MAIL_FROM: no-reply@system-alerts.local