apiVersion: v1
kind: Secret
metadata:
  name: dsbd-secrets
  namespace: dsbd
type: Opaque
stringData:
  DB_PASSWORD: password

  OPENSKY_CLIENT_ID: your_client_id
  OPENSKY_CLIENT_SECRET: your_client_secret

  MAIL_USERNAME: your_mailtrap_username
  MAIL_PASSWORD: your_mailtrap_password