version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      # Healthcheck sul database 'POSTGRES_DB' usando le credenziali di ambiente
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-manager-service:
    build:
      context: ../user-manager-service
      dockerfile: Dockerfile
    container_name: user_manager
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./env/services.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"

  data-collector-service:
    build:
      context: ../data-collector-service
      dockerfile: Dockerfile
    container_name: data_collector
    depends_on:
      postgres:
        condition: service_healthy
      user-manager-service:
        condition: service_started
    env_file:
      - ./env/services.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"