version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dsbd_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # POSTGRES_DB non Ã¨ obbligatorio; useremo uno script di init per creare i DB applicativi
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  user-manager-service:
    build: ../user-manager-service
    depends_on:
      - postgres

  data-collector-service:
    build: ../data-collector-service
    depends_on:
      - postgres
      - user-manager-service
