apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-service
  namespace: dsbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager-service
  template:
    metadata:
      labels:
        app: user-manager-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z postgres 5432; do echo 'attendo postgres...'; sleep 2; done"]
      containers:
        - name: user-manager-service
          image: dsbd/user-manager-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          envFrom:
            - configMapRef:
                name: dsbd-config
            - secretRef:
                name: dsbd-secrets
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10