apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
  namespace: dsbd
spec:
  selector:
    app: user-manager-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9090
      targetPort: 9090