apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-zookeeper-deployment.yaml
  - 02-zookeeper-service.yaml
  - 03-kafka-deployment.yaml
  - 04-kafka-service.yaml
  - 05-kafka-ui-deployment.yaml
  - 06-kafka-ui-service.yaml