apiVersion: v1
kind: Service
metadata:
  name: alert-system-service
  namespace: dsbd
  labels:
    app: alert-system-service
spec:
  type: ClusterIP
  selector:
    app: alert-system-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP